In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X = df.drop('species', axis=1)
y = df['species']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
model_knn = KNeighborsClassifier(n_neighbors=13)

In [10]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [11]:
model_knn.score(X_test,y_test)

1.0

In [12]:
from sklearn.svm import SVC

In [13]:
model_svc = SVC(gamma= 'auto')

In [14]:
model_svc.fit(X_train,y_train)

SVC(gamma='auto')

In [15]:
model_svc.score(X_test,y_test)

1.0

In [16]:
#now lets use the grid search CV

In [17]:
from sklearn.model_selection import GridSearchCV

In [18]:
classifier = GridSearchCV(model_svc,{
    'C' : [1,10,20,30],
    'kernel' :['rbf','linear'],
},cv = 5,return_train_score = False)

In [19]:
classifier.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [20]:
classifier.cv_results_

{'mean_fit_time': array([0.0078742 , 0.0060842 , 0.00918055, 0.00556974, 0.01521029,
        0.01579781, 0.00640044, 0.0085115 ]),
 'std_fit_time': array([0.00314235, 0.00190773, 0.00478365, 0.00260806, 0.00383127,
        0.00642456, 0.00258791, 0.00360786]),
 'mean_score_time': array([0.00545106, 0.00575809, 0.00813432, 0.00432367, 0.00942907,
        0.00984983, 0.00485945, 0.00462451]),
 'std_score_time': array([0.00194174, 0.00304225, 0.00586065, 0.00162709, 0.00263029,
        0.00417561, 0.00104327, 0.00116611]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([1.        , 1.        , 1.        , 1.        , 0.95833333,
        0.95833333, 0.95833333, 0.95833333]),
 'split1_test_score': array([0.95833333, 0.95833333, 0.95833333, 0.95833333, 0.95833333,
        0.95833333, 0.95833333, 0.95833333]),
 'split2_test_score': array([0.83333333, 0.875     , 0.83333333, 0.83333333, 0.83333333,
        0.83333333, 0.83333333, 0.83333333]),
 'split3_test_score': array([1.        , 1.        , 1.        , 0.95833333, 1.        ,
        1.        , 1.        , 0.95833333]),
 'split4_test_score': array([0.95833333, 0.95833333, 1.        , 1.        , 1.        ,
        1.        , 0.95833333, 1.        ]),
 'mean_test_score': array([0.95      , 0.95833333, 0.95833333, 0.95      , 0.95      ,
        0.95      , 0.94166667, 0.94166667]),
 'std_test_score': array([0.06123724, 0.04564355, 0.06454972, 0.06123724, 0.06123724,
        0.06123724, 0.05651942, 0.05651942]),
 'rank_test_score': array([3, 1, 1, 3, 3, 3, 8, 7], dtype=int32)}

In [22]:
results = pd.DataFrame(classifier.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.007874,0.003142,0.005451,0.001942,1,rbf,"{'C': 1, 'kernel': 'rbf'}",1.000000,0.958333,0.833333,1.000000,0.958333,0.950000,0.061237,3
1,0.006084,0.001908,0.005758,0.003042,1,linear,"{'C': 1, 'kernel': 'linear'}",1.000000,0.958333,0.875000,1.000000,0.958333,0.958333,0.045644,1
2,0.009181,0.004784,0.008134,0.005861,10,rbf,"{'C': 10, 'kernel': 'rbf'}",1.000000,0.958333,0.833333,1.000000,1.000000,0.958333,0.064550,1
3,0.005570,0.002608,0.004324,0.001627,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,0.958333,0.833333,0.958333,1.000000,0.950000,0.061237,3
4,0.015210,0.003831,0.009429,0.002630,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.958333,0.958333,0.833333,1.000000,1.000000,0.950000,0.061237,3
5,0.015798,0.006425,0.009850,0.004176,20,linear,"{'C': 20, 'kernel': 'linear'}",0.958333,0.958333,0.833333,1.000000,1.000000,0.950000,0.061237,3
6,0.006400,0.002588,0.004859,0.001043,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.958333,0.958333,0.833333,1.000000,0.958333,0.941667,0.056519,8
7,0.008511,0.003608,0.004625,0.001166,30,linear,"{'C': 30, 'kernel': 'linear'}",0.958333,0.958333,0.833333,0.958333,1.000000,0.941667,0.056519,7

In [23]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.950000
1        1       linear         0.958333
2       10          rbf         0.958333
3       10       linear         0.950000
4       20          rbf         0.950000
5       20       linear         0.950000
6       30          rbf         0.941667
7       30       linear         0.941667

In [24]:
from sklearn.model_selection import RandomizedSearchCV

In [26]:
classifier_r = RandomizedSearchCV((model_svc),{
    'C' : [1,10,20,30],
    'kernel' :['rbf','linear'],
},n_iter = 4,cv = 5,return_train_score = False)

In [27]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [28]:
results = pd.DataFrame(classifier_r.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.008283,0.003972,0.006928,0.004660,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.004909,0.000163,0.003515,0.000073,linear,30,"{'kernel': 'linear', 'C': 30}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,4
2,0.004717,0.000370,0.003392,0.000145,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,3
3,0.008333,0.005258,0.005060,0.002359,linear,1,"{'kernel': 'linear', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1

In [29]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       10          rbf         0.980000
1       30       linear         0.960000
2       20          rbf         0.966667
3        1       linear         0.980000

In [30]:
#ensemble learning

In [31]:
df = sns.load_dataset('iris')

In [32]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [33]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import StackingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [34]:
X = df.drop('species', axis=1)
y = df['species']

In [35]:

le = LabelEncoder()
y_encoded = le.fit_transform(y)

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded)

In [37]:

base_learners = [
    ('dt', DecisionTreeClassifier(random_state=42)),
    ('svc', SVC(probability=True, kernel='rbf', random_state=42)),
    ('lr', LogisticRegression(max_iter=1000))
]

In [38]:

meta_learner = LogisticRegression(max_iter=1000)

In [39]:
stacking_clf = StackingClassifier(
    estimators=base_learners,
    final_estimator=meta_learner,
    cv=5
)

In [40]:
stacking_clf.fit(X_train, y_train)

StackingClassifier(cv=5,
                   estimators=[('dt', DecisionTreeClassifier(random_state=42)),
                               ('svc', SVC(probability=True, random_state=42)),
                               ('lr', LogisticRegression(max_iter=1000))],
                   final_estimator=LogisticRegression(max_iter=1000))

In [41]:
y_pred = stacking_clf.predict(X_test)

In [42]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9666666666666667

In [43]:
from sklearn.ensemble import RandomForestClassifier

In [44]:
rf_model = RandomForestClassifier(
    n_estimators=100,     # number of trees
    max_depth=None,       # let trees grow fully
    random_state=42,

)

In [45]:
rf_model.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [46]:
y_pred = rf_model.predict(X_test)

In [47]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9